<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240509102104 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dmarc_records ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dmarc_reports ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dmarc_results ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE domains ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE logs ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE mxrecords ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE smtptls_failure_details ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE smtptls_mxrecords ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE smtptls_policies ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE smtptls_rdata_records ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE smtptls_reports ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE dmarc_results ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE mxrecords ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE domains ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE smtptls_rdata_records ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dmarc_records ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE smtptls_mxrecords ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dmarc_reports ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE smtptls_policies ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE logs ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE smtptls_reports ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE smtptls_failure_details ALTER id DROP IDENTITY');
    }
}
